runtime: nodejs18
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: "301"
  - url: .*
    script: auto
  - url: .*
    script: auto
  - url: .*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 1
service_account: eduquest-app-v1@appspot.gserviceaccount.com
